version: '3.8'

services:
  malla-web:
    image: ghcr.io/zenitram/malla:latest
    ports:
      - "5008:5008"
    environment:
      - MALLA_HOST=0.0.0.0
      - MALLA_PORT=5008
      - MALLA_DATABASE_FILE=/app/data/meshtastic_history.db
      - MALLA_NAME=Malla
    volumes:
      - ./data:/app/data
      # Optional: mount your own config file
      # - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    depends_on:
      - malla-capture

  malla-capture:
    image: ghcr.io/zenitram/malla:latest
    command: ["uv", "run", "./malla-capture"]
    environment:
      - MALLA_DATABASE_FILE=/app/data/meshtastic_history.db
      # Configure your MQTT broker settings here:
      - MALLA_MQTT_BROKER_ADDRESS=${MALLA_MQTT_BROKER_ADDRESS:-127.0.0.1}
      - MALLA_MQTT_PORT=${MALLA_MQTT_PORT:-1883}
      - MALLA_MQTT_USERNAME=${MALLA_MQTT_USERNAME:-}
      - MALLA_MQTT_PASSWORD=${MALLA_MQTT_PASSWORD:-}
      # Optional additional settings:
      # - MALLA_MQTT_TOPIC_PREFIX=msh
      # - MALLA_DEFAULT_CHANNEL_KEY=1PG7OiApB1nwvP+rz05pAQ==
    volumes:
      - ./data:/app/data
      # Optional: mount your own config file
      # - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped

volumes:
  data:
